# Generated by Django 4.2.2 on 2023-06-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_max', models.DecimalField(decimal_places=2, max_digits=4)),
                ('temp_min', models.DecimalField(decimal_places=2, max_digits=4)),
                ('wind', models.DecimalField(decimal_places=2, max_digits=4)),
                ('prediction', models.CharField(choices=[(1, 'Rain'), (2, 'Sun'), (3, 'Fog'), (4, 'Drizzle'), (5, 'Snow')], max_length=10)),
            ],
        ),
    ]
